name: Generate POT file
on:
  pull_request:
    branches: [ master ]

jobs:
  WP_Generate_POT_File:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress .pot File Generator
      uses: iamdharmesh/action-wordpress-pot-generator@main
      with:
        destination_path: './languages'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
